services:
  backend:
    image: golang:1.24
    depends_on:
      - postgres
    environment:
      - DB_POSTGRESQL_DATABASE=postgres
      - DB_POSTGRESQL_HOST=postgres
      - DB_POSTGRESQL_PORT=5432
      - DB_POSTGRESQL_USERNAME=postgres
      - DB_POSTGRESQL_SSL=false
    ports:
      - "8000:8000"
    command: go run -mod=vendor ./cmd
    volumes:
      - .:/app
    working_dir: /app
  postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-p", "5432", "-c", "log_statement=all"]
    ports:
      - "8543:5432"
