// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Account struct {
	ID        string    `json:"id"`
	AuthID    string    `json:"authID"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type AccountInput struct {
	ID string `json:"id"`
}

type AccountResponse struct {
	Account *Account `json:"account"`
}

type Mutation struct {
}

type Payment struct {
	ID          string    `json:"id"`
	Amount      string    `json:"amount"`
	ReferenceID string    `json:"referenceID"`
	AccountID   string    `json:"accountID"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type PaymentInput struct {
	ID string `json:"id"`
}

type PaymentResponse struct {
	Payment *Payment `json:"payment"`
}

type Query struct {
}
